alphagov/govuk_ab_testing

README.md
lib/govuk_ab_testing/ab_test.rb
lib/govuk_ab_testing/requested_variant.rb
spec/requested_variant_spec.rb

Remove automatic capitalization of test names, so the test name you specify matches the cookie name and meta tag exactly.
- Removes ambiguity about the capitalization, which makes it easier to configure the CDN cookie config so that it matches the test name.
- Gives users more control over the test name, which needs to be readable in the Google Analytics results and in the Chrome extension.
I'm just a bit worried the capitalization would trip someone up when they're configuring the cookie in the CDN.

	Make A/B test names case-sensitive

---

Jenkinsfile
Rakefile
govuk_ab_testing.gemspec

This Pull Request is part of the work to publish the [AB Testing Gem](https://github.com/alphagov/govuk_ab_testing) to [RubyGems.org](http://rubygems.org).
This adds a `Jenkinsfile` for building on Jenkins 2, as well as a rake task for publishing the gem. This is a direct readacross of `govuk_navigation_helpers`. The migration to Jenkins 2 is here: https://github.com/alphagov/govuk_navigation_helpers/pull/20
Trello: https://trello.com/c/tclzOZ7Z/382-release-govuk-ab-testing-to-rubygems

CI and gem publishing

---

govuk_ab_testing.gemspec

This fixes the Jenkins branch builds.
We didn't spot this when adding the Jenkinsfile because the master build skips the linting step.

Add missing govuk-lint dependency

---

.rubocop.yml
README.md
lib/govuk_ab_testing/ab_test.rb
lib/govuk_ab_testing/minitest_helpers.rb
lib/govuk_ab_testing/requested_variant.rb
spec/minitest_helpers_spec.rb
spec/requested_variant_spec.rb

Make the dimension a required parameter when configuring a test, because we expect every A/B test to report its results to Google Analytics.
Include the dimension in the `meta` tag, so that the GA JavaScript will report the user's variant using the correct GA dimension. This matches the format proposed in alphagov/static#890.
Trello: https://trello.com/c/g9OyC7Pn/310-tell-google-analytics-about-a-b-tests

Configure Google Analytics dimension for A/B test

---

lib/govuk_ab_testing/minitest_helpers.rb
lib/govuk_ab_testing/requested_variant.rb
spec/requested_variant_spec.rb
spec/spec_helper.rb

As suggested in https://github.com/alphagov/govuk_ab_testing/pull/1#discussion_r99109109 we can merge the `Vary` headers if they exist.

Merge Vary HTTP headers

---

lib/govuk_ab_testing/minitest_helpers.rb

Rename helper to make its purpose clearer to people who don't know the details of A/B testing.
Suggested in alphagov/collections#232.
This changes the API of the gem, but we're still pre-1.0 and I think my redirects PR is the only thing which relies on it.

Improve test helper name

---

Jenkinsfile

The gem doesn't depend on Rails, so there's no need to set a Rails environment variable when running the tests.

Delete unnecessary CI step

---

README.md
lib/govuk_ab_testing.rb
lib/govuk_ab_testing/minitest_helpers.rb
lib/govuk_ab_testing/rspec_capybara_helpers.rb
spec/minitest_helpers_spec.rb
spec/rspec_capybara_helpers_spec.rb
spec/spec_helper.rb
spec/support/fake_capybara_page.rb
spec/support/fake_minitest_controller_test_case.rb

In this PR:
- New helper class to add `with_variant` to RSpec + Capybara tests;
- Test presence of custom dimension in analytics meta tag.
Trello: https://trello.com/c/V6PSacVC/336-changes-to-education-related-content-pages-as-part-of-the-new-navigation-in-manuals-frontend

Include capybara helpers

---

README.md

`assert_unaffected_by_ab_test` no longer exists, as it has been renamed.
This commit makes sure we have an up-to-date README.

Fix name of assertion method in README

---

lib/govuk_ab_testing/acceptance_tests/active_support.rb
lib/govuk_ab_testing/acceptance_tests/capybara.rb

If we use `with_variant` more than once in a test case, we would keep
the old value set and the tests could potentially fail.
Trello: https://trello.com/c/t4n8kPpx/434-make-sure-collections-can-be-toggled-with-the-a-b-test-and-react-to-it
This is the cause of a bug reported here: https://github.com/alphagov/government-frontend/pull/264#discussion_r103697916

Avoid memoising meta tags

---

lib/govuk_ab_testing/minitest_helpers.rb

Update `assert_response_not_modified_for_ab_test` so that it inspects the headers and meta tags using the test framework in the same way as the other test helpers.
@carvil Could you check that I've done the right thing here? I've tested it in both collections and frontend, which use different integration test frameworks.

Ensure all test helpers are test framework-agnostic

---

README.md
lib/govuk_ab_testing/minitest_helpers.rb

Add two new Minitest helpers:
- Test that the `Vary` header is added
- Test that the `meta` tag is not added
These can be used to test cases like the Education Navigation on the homepage, where we want to cache the variants separately not but include them in the analytics.
https://trello.com/c/FOUYzmzX/477-change-homepage-topic-and-description-for-education

Add more fine-grained test helpers

---

CHANGELOG.md
README.md
lib/govuk_ab_testing/rspec_helpers.rb
lib/govuk_ab_testing/version.rb

Add the fine-grained setup and assertion steps to the RSpec test helper so that they can be used from applications like manuals-frontend.
https://trello.com/c/Xehe42eM/464-only-add-a-b-meta-tag-to-pages-in-the-navigation-a-b-test

Port individual assertions from Minitest to RSpec

---

CHANGELOG.md
README.md
lib/govuk_ab_testing.rb
lib/govuk_ab_testing/acceptance_tests/active_support.rb
lib/govuk_ab_testing/acceptance_tests/capybara.rb
lib/govuk_ab_testing/acceptance_tests/meta_tag.rb
lib/govuk_ab_testing/minitest_helpers.rb
lib/govuk_ab_testing/rspec_helpers.rb
spec/meta_tag_spec.rb
spec/support/fake_minitest_controller_test_case.rb

This commit modifies the following assertions in both `Minitest` and
`RSpec` classes:
- `assert_response_is_cached_by_variant`
- `assert_response_not_modified_for_ab_test`
Both assertions now require a new parameter `ab_test_name`, which
indicates what A/B test we are running the assertions against.
This change is needed in case we are running more than 1 A/B test in a
given page.
This commit also introduces a `MetaTag` class which allows us to query
if a given meta tag belongs to a particular A/B test.
Related trello card: https://trello.com/c/NJ6O76BR/281-heatmap-tracking

Modify assertions to require A/B test name

---

lib/govuk_ab_testing/abstract_helpers.rb
lib/govuk_ab_testing/minitest_assertions.rb

- Removed string interpolation for parameters that may potentially be nil in some test uses.
- Add key name parameters for helper methods that require it.
https://trello.com/c/43eBQfwf/80-prepare-the-infrastructure-for-the-minimum-should-match-a-b-test

Fix empty assertion helper

---

lib/govuk_ab_testing/acceptance_tests/active_support.rb

Upgrading to Rails 5.0.2 appears to break the AB Test helpers.
It appears that the `@response` object is being reassigned midway
through tests.
The Active Support helper previously memoized the `@request` and
`@response` objects. However, since these objects appear to change
partway through the tests, the test helper then references the “wrong”
object.
This change forces us to look up the `@request` and `@response` objects
each time they are requested of the test helper.

Don’t memoize Active Support request/response in test helpers

---

CHANGELOG.md
lib/govuk_ab_testing/acceptance_tests/capybara.rb
spec/acceptance_tests/capybara_spec.rb

Currently, we were overriding the headers when setting them in Capybara.
Now that we have applications adding more than 1 A/B test at once, we
need to retain the information about all A/B tests in the headers for
the tests to work.
Related to work being done on this trello card: https://trello.com/c/S5jp2jih/179-setup-technical-implementation-for-a-b-testing-the-blue-box

Allow multiple headers to be set in Capybara

---

CHANGELOG.md
README.md
lib/govuk_ab_testing/ab_test.rb
lib/govuk_ab_testing/requested_variant.rb
spec/requested_variant_spec.rb

In this PR, I've:
- Introduce a new method called `variant?(name)`;
- deprecates `variant_a?` and `variant_b?`;
- allow for custom variant names;
- allow for an arbitrary number of variants (multivariate testing). 
The new method `variant?(name)` allows for generic variant names to be used in A/B tests besides just A and B. The reason for this is so we can re-use a generic A/B test setup across different A/B tests. In the Navigation team, we have 1 long running A/B test for the new navigation called `EducationNavigation`. We would like to conduct other short-lived A/B tests within to improve the new navigation. Because of limitations in the number of custom dimensions we can have in Google Analytics, we agreed to create one generic A/B test (`NavigationTest`) and recycle it when we are …

Allow for custom variant names in A/B tests

---

CHANGELOG.md
README.md
lib/govuk_ab_testing/acceptance_tests/active_support.rb
spec/support/fake_minitest_controller_test_case.rb

Add extra validation to ActiveSupport assertions to help debug test failures.
In order to make assertions about the `meta` tags, the view must be rendered in the test. RSpec Rails tests do not do this by default, so you need to call `render_views` explicitly. Without this check, tests fail with a cryptic error message "undefined method 'document' for nil:NilClass".
Also add an RSpec Rails example to the README.
https://trello.com/c/JJ3mIOP1/392-configure-format-weighting-a-b-test-in-frontend
cc @brenetic

 Check page body exists before running assertions

---

CHANGELOG.md
lib/govuk_ab_testing/version.rb

* Updated gem dependencies and development ruby version to 2.6.6
* Fixed new rubocop violations

Bump to 2.4.2

---

.github/workflows/ci.yml
Jenkinsfile

As per RFC-123 we're moving away from Jenkins for testing and publishing our gems
Once approved, this will require someone with the relevant access to:
* remove branch protection
* add github actions secret
before merging.
[Trello](https://trello.com/c/QrxjshEm/270-move-ruby-gems-from-jenkins-to-github-actions)

Add github actions config and remove jenkinsfile

---

CHANGELOG.md
README.md
lib/govuk_ab_testing/ab_test.rb
lib/govuk_ab_testing/abstract_helpers.rb
lib/govuk_ab_testing/acceptance_tests/active_support.rb
lib/govuk_ab_testing/acceptance_tests/capybara.rb
lib/govuk_ab_testing/acceptance_tests/meta_tag.rb
lib/govuk_ab_testing/requested_variant.rb
spec/meta_tag_spec.rb
spec/requested_variant_spec.rb
spec/rspec_helpers_spec.rb
spec/support/fake_capybara_page.rb
spec/support/fake_minitest_controller_test_case.rb

Universal Analytics has been replaced by Google Analytics 4. 
The custom dimension was a required field for UA, and is no longer needed by GA4 which processes events differently.

Remove custom dimension from AB test configuration

---

CHANGELOG.md
lib/govuk_ab_testing/version.rb

* Drop support for Ruby 3.0. The minimum required Ruby version is now 3.1
* **BREAKING CHANGE** No longer allow a GA custom dimension to be passed when creating a GovukAbTesting::AbTest object. The dimension parameter needs to be removed.

Release 3.0.0
